# fly.toml app configuration file generated for trackerito on 2024-01-07T17:37:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "trackerito"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
